In [23]:
import pandas as pd

In [24]:
arquivo = 'arxiv_data.csv'

data = pd.read_csv(arquivo)

In [25]:
data

,ids,titles,abstracts,astro-ph.CO,astro-ph.EP,astro-ph.GA,astro-ph.HE,astro-ph.IM,astro-ph.SR,cond-mat.dis-nn,...,q-fin.RM,q-fin.ST,q-fin.TR,quant-ph,stat.AP,stat.CO,stat.ME,stat.ML,stat.OT,stat.TH
0,1809.10336,Multi-task Learning for Financial Forecasting,Financial forecasting is challenging and att...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,2305.11021,The Wisdom of Strategic Voting,We study the voting game where agents' prefe...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1704.00646,A correlation game for unsupervised learning y...,Much has been learned about plasticity of bi...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2104.03906,Explaining decisions made with AI: A workbook ...,"Over the last two years, The Alan Turing Ins...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1207.63610,Magneto-elastic coupling in the spin-Peierls g...,We report an ultrasonic study of the magneto...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536909,2009.14587,Pointwise Universal Gysin formulae and Applica...,"Let $X$ be a complex manifold, $(E,h)\to X$ ...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536910,2104.07090,On a notion of ring groupoid,By a ring groupoid we mean an animated ring ...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536911,1708.04218,"From Gap-ETH to FPT-Inapproximability: Clique,...",We consider questions that arise from the in...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536912,1406.32070,Markov traces on affine and cyclotomic Yokonum...,"In this article, we define and study the aff...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536913,2401.01512,Which Syntactic Capabilities Are Statistically...,This paper discusses the limitations of eval...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Obtemos os nomes das colunas

In [26]:
variaveis = data.columns.to_list()
variaveis

['ids',
 'titles',
 'abstracts',
 'astro-ph.CO',
 'astro-ph.EP',
 'astro-ph.GA',
 'astro-ph.HE',
 'astro-ph.IM',
 'astro-ph.SR',
 'cond-mat.dis-nn',
 'cond-mat.mes-hall',
 'cond-mat.mtrl-sci',
 'cond-mat.other',
 'cond-mat.quant-gas',
 'cond-mat.soft',
 'cond-mat.stat-mech',
 'cond-mat.str-el',
 'cond-mat.supr-con',
 'cs.AI',
 'cs.AR',
 'cs.CC',
 'cs.CE',
 'cs.CG',
 'cs.CL',
 'cs.CR',
 'cs.CV',
 'cs.CY',
 'cs.DB',
 'cs.DC',
 'cs.DL',
 'cs.DM',
 'cs.DS',
 'cs.ET',
 'cs.FL',
 'cs.GL',
 'cs.GR',
 'cs.GT',
 'cs.HC',
 'cs.IR',
 'cs.IT',
 'cs.LG',
 'cs.LO',
 'cs.MA',
 'cs.MM',
 'cs.MS',
 'cs.NA',
 'cs.NE',
 'cs.NI',
 'cs.OH',
 'cs.OS',
 'cs.PF',
 'cs.PL',
 'cs.RO',
 'cs.SC',
 'cs.SD',
 'cs.SE',
 'cs.SI',
 'cs.SY',
 'econ.EM',
 'econ.GN',
 'econ.TH',
 'eess.AS',
 'eess.IV',
 'eess.SP',
 'eess.SY',
 'gr-qc',
 'hep-ex',
 'hep-lat',
 'hep-ph',
 'hep-th',
 'math-ph',
 'math.AC',
 'math.AG',
 'math.AP',
 'math.AT',
 'math.CA',
 'math.CO',
 'math.CT',
 'math.CV',
 'math.DG',
 'math.DS',
 'math.FA',
 'math.GM',
 'math.GN',
 'math.GR',
 'math.GT',
 'math.HO',
 'math.IT',
 'math.KT',
 'math.LO',
 'math.MG',
 'math.MP',
 'math.NA',
 'math.NT',
 'math.OA',
 'math.OC',
 'math.PR',
 'math.QA',
 'math.RA',
 'math.RT',
 'math.SG',
 'math.SP',
 'math.ST',
 'nlin.AO',
 'nlin.CD',
 'nlin.CG',
 'nlin.PS',
 'nlin.SI',
 'nucl-ex',
 'nucl-th',
 'physics.acc-ph',
 'physics.ao-ph',
 'physics.app-ph',
 'physics.atm-clus',
 'physics.atom-ph',
 'physics.bio-ph',
 'physics.chem-ph',
 'physics.class-ph',
 'physics.comp-ph',
 'physics.data-an',
 'physics.ed-ph',
 'physics.flu-dyn',
 'physics.gen-ph',
 'physics.geo-ph',
 'physics.hist-ph',
 'physics.ins-det',
 'physics.med-ph',
 'physics.optics',
 'physics.plasm-ph',
 'physics.pop-ph',
 'physics.soc-ph',
 'physics.space-ph',
 'q-bio.BM',
 'q-bio.CB',
 'q-bio.GN',
 'q-bio.MN',
 'q-bio.NC',
 'q-bio.OT',
 'q-bio.PE',
 'q-bio.QM',
 'q-bio.SC',
 'q-bio.TO',
 'q-fin.CP',
 'q-fin.EC',
 'q-fin.GN',
 'q-fin.MF',
 'q-fin.PM',
 'q-fin.PR',
 'q-fin.RM',
 'q-fin.ST',
 'q-fin.TR',
 'quant-ph',
 'stat.AP',
 'stat.CO',
 'stat.ME',
 'stat.ML',
 'stat.OT',
 'stat.TH']

In [27]:
colunasIniciais = ['ids', 'titles', 'abstracts']
categorias_interesses = ["cs.CV","stat.ML","quant-ph","cs.LG","cs.AI","math.ST","physics.optics","cs.DB"]
colunasMantidas = colunasIniciais + categorias_interesses

In [28]:
colunasExcluir = [colunas for colunas in variaveis if colunas not in colunasMantidas]

In [29]:
data_final = data.drop(columns=colunasExcluir)
data_final

,ids,titles,abstracts,cs.AI,cs.CV,cs.DB,cs.LG,math.ST,physics.optics,quant-ph,stat.ML
0,1809.10336,Multi-task Learning for Financial Forecasting,Financial forecasting is challenging and att...,1,0,0,1,0,0,0,1
1,2305.11021,The Wisdom of Strategic Voting,We study the voting game where agents' prefe...,0,0,0,0,0,0,0,0
2,1704.00646,A correlation game for unsupervised learning y...,Much has been learned about plasticity of bi...,0,0,0,0,0,0,0,0
3,2104.03906,Explaining decisions made with AI: A workbook ...,"Over the last two years, The Alan Turing Ins...",0,0,1,1,0,0,0,0
4,1207.63610,Magneto-elastic coupling in the spin-Peierls g...,We report an ultrasonic study of the magneto...,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
536909,2009.14587,Pointwise Universal Gysin formulae and Applica...,"Let $X$ be a complex manifold, $(E,h)\to X$ ...",0,0,0,0,0,0,0,0
536910,2104.07090,On a notion of ring groupoid,By a ring groupoid we mean an animated ring ...,0,0,0,0,0,0,0,0
536911,1708.04218,"From Gap-ETH to FPT-Inapproximability: Clique,...",We consider questions that arise from the in...,0,0,0,0,0,0,0,0
536912,1406.32070,Markov traces on affine and cyclotomic Yokonum...,"In this article, we define and study the aff...",0,0,0,0,0,0,0,0
536913,2401.01512,Which Syntactic Capabilities Are Statistically...,This paper discusses the limitations of eval...,0,0,0,0,0,0,0,0

In [30]:
data_final = data_final.sample(frac = 0.1, random_state=42)
data_final

,ids,titles,abstracts,cs.AI,cs.CV,cs.DB,cs.LG,math.ST,physics.optics,quant-ph,stat.ML
233419,2107.14624,Convergent Star Products on Cotangent Bundles ...,For a connected real Lie group $G$ we consid...,0,0,0,0,0,0,0,0
190465,2308.14524,Towards enabling reliable immersive teleoperat...,This paper addresses the challenging problem...,0,0,0,0,0,0,0,0
420387,1611.04918,Ultrametricity of optimal transport substates ...,We model a set of point-to-point transports ...,0,0,0,0,0,0,0,0
425806,2306.17702,Why Deep Models Often cannot Beat Non-deep Cou...,Molecular property prediction (MPP) is a cru...,0,0,0,1,0,0,0,0
187069,1706.00127,The interplay between Steinberg algebras and p...,We study the interplay between Steinberg alg...,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
327022,2303.03700,EavesDroid: Eavesdropping User Behaviors via O...,As the Internet of Things (IoT) continues to...,0,0,0,0,0,0,0,0
47698,2010.15801,Ray-marching Thurston geometries,We describe algorithms that produce accurate...,0,0,0,0,0,0,0,0
175301,1109.03730,Nonconventional limit theorems in averaging,"We consider ""nonconventional"" averaging setu...",0,0,0,0,0,0,0,0
421201,1207.08270,On $\infty$-convex sets in spaces of scattered...,"Given a topological space $X$, we study the ...",0,0,0,0,0,0,0,0
130580,2308.15870,Deontic Paradoxes in ASP with Weak Constraints,The rise of powerful AI technology for a ran...,1,0,0,0,0,0,0,0

In [31]:
colunas_de_categoria = data_final.columns[3:]
colunas_de_categoria
mascara_para_manter = (data_final[colunas_de_categoria] == 1).any(axis=1)

In [32]:
data_final = data_final[mascara_para_manter]
data_final

,ids,titles,abstracts,cs.AI,cs.CV,cs.DB,cs.LG,math.ST,physics.optics,quant-ph,stat.ML
425806,2306.17702,Why Deep Models Often cannot Beat Non-deep Cou...,Molecular property prediction (MPP) is a cru...,0,0,0,1,0,0,0,0
342964,2203.06430,Categories of Differentiable Polynomial Circui...,Reverse derivative categories (RDCs) have re...,0,0,0,1,0,0,0,0
137083,2307.04400,ARK: Robust Knockoffs Inference with Coupling,We investigate the robustness of the model-X...,0,0,0,0,1,0,0,1
521807,2310.16175,G-CASCADE: Efficient Cascaded Graph Convolutio...,"In recent years, medical image segmentation ...",0,1,0,1,0,0,0,0
183631,1310.76720,Intrinsic Contextuality as the Crux of Conscio...,A stream of conscious experience is extremel...,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
167765,2201.00889,Biased Hypothesis Formation From Projection Pu...,The effect of bias on hypothesis formation i...,0,0,0,1,0,0,0,1
210663,1510.07298,Experimental system design for the integration...,We present a design for the experimental int...,0,0,0,0,0,0,1,0
519096,2207.04941,Wavelet Conditional Renormalization Group,We develop a multiscale approach to estimate...,0,0,0,1,0,0,0,0
306323,2012.12103,Fabrication of Ge2Sb2Te5 metasurfaces by direc...,We experimentally demonstrate fabrication of...,0,0,0,0,0,1,0,0
130580,2308.15870,Deontic Paradoxes in ASP with Weak Constraints,The rise of powerful AI technology for a ran...,1,0,0,0,0,0,0,0

In [33]:
nome_do_arquivo = 'dados_tratados.csv'

data_final.to_csv(nome_do_arquivo, index=False, encoding='utf-8')